# Generated by Django 3.2.8 on 2021-10-05 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='credentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('occasion', models.CharField(max_length=64)),
                ('det', models.CharField(max_length=64)),
            ],
        ),
    ]
