# Generated by Django 3.2.8 on 2021-10-05 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='credentials',
            new_name='credential',
        ),
    ]
