# Generated by Django 3.2.7 on 2021-10-13 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0002_rename_credentials_credential'),
    ]

    operations = [
        migrations.CreateModel(
            name='bday_credential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('address', models.CharField(max_length=200)),
                ('contact', models.IntegerField()),
                ('date', models.DateField()),
                ('occasion', models.CharField(max_length=64)),
                ('age', models.IntegerField()),
                ('time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='gath_credential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occasion', models.CharField(max_length=64)),
                ('address', models.CharField(max_length=200)),
                ('contact', models.IntegerField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='wed_credential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groom', models.CharField(max_length=64)),
                ('bride', models.CharField(max_length=64)),
                ('address', models.CharField(max_length=200)),
                ('contact', models.IntegerField()),
                ('date', models.DateField()),
                ('occasion', models.CharField(max_length=64)),
                ('time', models.TimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='credential',
        ),
    ]
